name: Deploy Integrated dashboard API
on:
  push:
    branches: [ main ]
jobs:

  build:
    name: Deploy API Updates
    runs-on: ubuntu-latest
    steps:
    - name: updating and deploying API
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          echo "connected."
